### PR TITLE
Prep for 3.2.0 release

### PR DESCRIPTION
**Pull request by jcarbaugh**
- Python 3.12 for dev and GitHub Actions
- Require Python >= 3.8
- Black formatting for Python 3.8 to 3.12
- Ignore .venv
- Convert README to markdown and update output examples
- Restore states script

https://test.pypi.org/project/us/3.2.0/

### CODE REVIEW

**Comment by pedrocamargo** [comment]
I'm happy to help

**Comment by jcarbaugh** [comment]
> I'm happy to help

Just sent a collaborator invite!

**Review by pedrocamargo — APPROVED** [review]

**Comment by pedrocamargo** [comment]
Done and dusted, @jcarbaugh . 

I just forgot to ask how you do things around here. We usually do where the reviewer merges and deletes the branch when they think it is good, so I did that.  I'm sorry if that's not your process here.

**Comment by jcarbaugh** [comment]
@pedrocamargo no set process here, appreciate the help! I'll get the release out shortly.

**Pull request merged**
