### PR TITLE
Jellyfish 1.x

### PR DESCRIPTION
**Pull request by dgilmanAIDENTIFIED**
This initial PR bumps jellyfish to 1.x, regenerates the lockfile, fixes CI, and adds the birthday constant. This is the first of the changes dug out from the big branch.

### CODE REVIEW

**Comment by OttoAndrey** [comment]
@jcarbaugh @pauldhawk pretty please 😇

**Comment by ngist** [comment]
+1 on this

**Comment by peterrrock2** [comment]
+1 Thank you for doing this!

**Comment by mrwbarg** [comment]
@jcarbaugh @pauldhawk @dgilmanAIDENTIFIED hey guys! any chance we can get this approved? It's blocking upgrading Python 3.11 -> 3.12 in projects which this depends on.

**Comment by dgilmanAIDENTIFIED** [comment]
I've been a bit busy lately but have plans soon / this weekend to review this project and get my changes merged one PR at a time. (I think the big one needed some more careful review). I've been added to this repo but I unfortunately do not yet have access to PyPI, however, once the repo is caught up I can ask again, or at the very least deploy a temporary fork.

**Pull request merged**
