### PR TITLE
Fixes for python-us

### LINKED ISSUE #14: https://en.wikipedia.org/wiki/America/Boise isn't in ID
Lawl.

Thanks @shanear!

### PR DESCRIPTION
**Pull request by dgilmanAIDENTIFIED**
Here are the fixes I've merged/made to python-us to get it up and working again. I have uploaded this to PyPI as package [`us-aidentified` version 3.0.1](https://pypi.org/project/us-aidentified/). Feel free to merge this or give any feedback on what you'd like to see for an official release.

#66: I merged this in
#64: close, this obsoletes it
#60: close, this fixes it

#65 close, this fixes it
#63 close, this obsoletes it
#58 close, this fixes it
#57 close, fixed in latest jellyfish
#56 close, this fixes it
#55 close, this fixes it
#54 I wrote a fix to this - turns out the cache wasn't running at all!
#52 I wrote a fix to this. Added a kwarg `additional_metaphones` to lookup() that takes a dict mapping metaphones to metaphones. I added a default dictionary with the Washington DC case, typos we've seen, and the Commonwealths. I think it's an OK fix but your input is welcome.
#33 I think the shapefile URLs take care of this?
#32 the DC_STATEHOOD envvar takes care of this, close
#14 and #15: close, this fixes it. I wrote a test that uses census shapefiles + the IANA timezone database to validate we have up-to-date timezones in each state.

### CODE REVIEW

**Comment by violuke** [comment]
Thank you @dgilmanAIDENTIFIED we've switched to your PiPy package for the time being :+1:

**Comment by jcarbaugh** [comment]
Hey @dgilmanAIDENTIFIED would you be open to being a maintainer of this package along with @pauldhawk?

**Comment by dgilmanAIDENTIFIED** [comment]
I'm OK with that. I slid into your DMs on Twitter to offer the same thing. If you can get us all in touch let's talk.

**Comment by pauldhawk** [comment]
@dgilmanAIDENTIFIED do you plan on finishing this  PR or should we close it?

**Comment by jcarbaugh** [comment]
@dgilmanAIDENTIFIED could you send me your email at jeremy@jcarbaugh.com so I can start a thread?

@pauldhawk I already have yours

**Comment by dgilmanAIDENTIFIED** [comment]
Email sent

**Pull request closed without merging**
