### PR TITLE
Python 3.12 support and software engineering

### PR DESCRIPTION
**Pull request by pedrocamargo**
This fixes #74, adding some software engineering in the process

### CODE REVIEW

**Comment by pauldhawk** [comment]
@pedrocamargo can you fix the merge conflicts. then I can approve.

**Review by pauldhawk — CHANGES_REQUESTED** [review]
Nice work please fix merge issues.

**Comment by pedrocamargo** [comment]
@pauldhawk , done.

**Comment by Artui** [comment]
@pauldhawk any estimates on when this will go out to PyPi with a new version? Thanks!

**Comment by pauldhawk** [comment]
A few days at most. We will get it done! Sorry about all the delays

**Review by pauldhawk — APPROVED** [review]

**Comment by jcarbaugh** [comment]
@pedrocamargo I've got a PR #79 up with some cleanup for a 3.2.0 release. If you'd be available to review it let me know and I'll add you to the project. Thanks!

**Pull request merged**
